import SwiftUI

extension Image {
    static let checkCircle = Image("CheckCircle")
    static let checkCircleFill = Image("CheckCircleFill")
    static let bell = Image("Bell")
    static let moreVert = Image("MoreVert")
    static let arrowForward = Image("ArrowForward")
    static let home = Image("Home")
    static let homeFill = Image("HomeFill")
    static let calendar = Image("Calendar")
    static let calendarFill = Image("CalendarFill")
    static let appjam = Image("Appjam")
    static let appjamFill = Image("AppjamFill")
    static let ellps = Image("Ellps")
    static let pencil = Image("Pencil")
    static let trash = Image("Trash")
    static let calendarFull = Image("CalendarFull")
    static let plus = Image("Plus")
    static let happyChar2 = Image("HappyChar2")
    static let happyFace = Image("Happy")
    static let normalFace = Image("Normal")
    static let goodFace = Image("Good")
    static let sadFace = Image("Sad")
    static let grumpyFace = Image("Grumpy")
    static let sample1 = Image("Sample1")
    static let sample2 = Image("Sample2")
    static let sample3 = Image("Sample3")
    static let sample4 = Image("Sample4")
}
